language: cpp
compiler: gcc
dist: bionic
sudo: true


addons:
  apt:
    packages: libopencv-dev libwxgtk3.0-dev libboost-all-dev clang-format colordiff lcov

script:
  - ./linter.sh
  - ./build.sh -c -d
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"